MARBLE-1197 Fix footer sx
ndlib/marble-website-starter pull request #373
Opened 2020-10-19 19:20 UTC by jmille79

2020-10-19 19:21 UTC, jmille79 commented
![Screen Shot 2020-10-19 at 3 02 08 PM](https://user-images.githubusercontent.com/38439231/96501710-b9c5d100-121e-11eb-85ae-391d1f45e81d.png)

2020-10-19 19:50 UTC, danthewolfe requested changes
Visually, looks much better. See comments for a few additional changes.

2020-10-19 19:50 UTC, danthewolfe commented on site/src/@ndlib/gatsby-theme-marble/components/Layout/PageWrapper/Footer/index.js
> +          <p className='contact-info'>
I've been getting the following warning: 
```
index.js:2177 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (at Footer/index.js:37)
    in p (at Footer/index.js:36)
```
So can we get the `<p/>`s here changed to `<div/>` or <span/>`?

2020-10-19 19:50 UTC, danthewolfe commented on site/src/@ndlib/gatsby-theme-marble/components/Layout/PageWrapper/Footer/sx.js
> +  }
Add trailing comma to line 48 to make hound happy.

2020-10-19 19:50 UTC, danthewolfe commented on site/src/@ndlib/gatsby-theme-marble/components/Layout/PageWrapper/Footer/index.js
>    return (
The line before code review starts contains an unused variable. Can we get this line removed?
```
  const date = new Date()
```

2020-10-20 12:39 UTC, danthewolfe approved these changes
See latest comment on one more `<p/>`, then 👍 .

2020-10-20 12:39 UTC, danthewolfe commented on site/src/@ndlib/gatsby-theme-marble/components/Layout/PageWrapper/Footer/index.js
> +          <p className='contact-info'>
Looks like you got the other instances of `<div/>` as a child of `<p/>`, get line 34 and line 41, then 👍 .

2020-10-20 13:08 UTC, mlkirkpatrick approved these changes

2020-10-20 13:10 UTC, SteveMattison approved these changes

2020-10-20 13:20 UTC, merged