MARBLE-1224 Beta Banner tweaks
ndlib/marble-website-starter pull request #390
Opened 2020-11-06 14:21 UTC by jmille79

2020-11-06 14:31 UTC, mlkirkpatrick approved these changes

2020-11-06 14:48 UTC, jmille79 commented
![image](https://user-images.githubusercontent.com/38439231/98379282-198cec00-2015-11eb-9558-b708f1253308.png)
![image](https://user-images.githubusercontent.com/38439231/98379353-30cbd980-2015-11eb-8e5e-8af6eb09e074.png)

2020-11-06 16:12 UTC, danthewolfe requested changes
See new mockups and Abby's requested text change: 
“This is a beta preview of the MARBLE website. Read about the project (link to microsite) or tell us what you think." (link to feedback form).
The updated banner should also appear on other pages under the search bar.

![Screen Shot 2020-11-06 at 9 57 26 AM](https://user-images.githubusercontent.com/416559/98388391-b1dc9e00-2020-11eb-85b4-ff9e350ae0f1.png)
![Screen Shot 2020-11-06 at 10 01 26 AM](https://user-images.githubusercontent.com/416559/98388393-b43ef800-2020-11eb-9cdd-b9a48be6d20f.png)

2020-11-09 18:35 UTC, danthewolfe approved these changes

2020-11-09 18:35 UTC, danthewolfe requested changes
Fix unit test then 👍

2020-11-09 20:27 UTC, merged