Move all classes in the Internal directory to the shared directory.
ndlib/marble-website-starter pull request #486
Opened 2021-03-04 18:51 UTC by jmille79

MARBLE-1453: Move all classes in the Internal directory to the shared directory.

2021-03-04 20:36 UTC, pweikel approved these changes

2021-03-04 21:59 UTC, danthewolfe requested changes
1. Pull: https://github.com/ndlib/marble-web/pull/40 and the changes I made here.
2. Confirm it builds locally for you:
```
yarn
npm rebuild --verbose sharp
yarn workspace marble clean
yarn workspace marble build
yarn workspace marble serve
```
3. Fix failing unit tests
4.  Then 👍

2021-03-05 16:02 UTC, danthewolfe approved these changes
@jmille79 Check w/ @jonhartzler before merging. Also make sure https://github.com/ndlib/marble-web/pull/40 gets merged at the same time.

2021-03-05 16:13 UTC, jmille79 commented
Related PRs: 
https://github.com/ndlib/inquisition/pull/18
https://github.com/ndlib/marble-web/pull/40

2021-03-05 17:47 UTC, merged