Remove 'X results in Y' from related items section
ndlib/marble-website-starter pull request #498
Opened 2021-03-15 17:43 UTC by jmille79

MARBLE-1255

2021-03-15 20:10 UTC, danthewolfe commented
> I guess I still have doubts that this is not going to just create a side effect later where the extra controls are not visible and they should be.
> 
> I think HitDisplay is going to need a parameter where you can turn this off and it may extend up to SearchResult
> @danthewolfe thoughts?



> I guess I still have doubts that this is not going to just create a side effect later where the extra controls are not visible and they should be.
> 
> I think HitDisplay is going to need a parameter where you can turn this off and it may extend up to SearchResult
> @danthewolfe thoughts?

Passing a parameter in directly is difficult because of the way that the Search results pieces are constructed in the the Searchkit library. That is why this was originally tied to the upgrade/migration of searchkit. I think the best work around for that might be to provide a context around that describes what features to include. 
https://reactjs.org/docs/context.html

Pseudocode:
on the search page something like:
```
const SearchContext = React.createContext('searchPage')

...

<SearchContext.Provider value="searchPage">
 <SearchResults ... />
</SearchContext.Provider>
``` 
and 
```
const SearchContext = React.createContext('itemPage')

...

<SearchContext.Provider value="itemPage">
 <SearchResults ... />
</SearchContext.Provider>
```

Then inside CardGroup:
```
const displayType = useContext(SearchContext)

...

<CardGroup
  defaultDisplay='list'
  toggleGroup='search'
  extraControls={displayType === 'searchPage ? SearchAdditionalTools : null}
   ...
/>
```

@jonhartzler  thoughts?

2021-03-31 15:45 UTC, jonhartzler requested changes
I think this will work but I think it also probably needs a unit test.

2021-04-07 13:18 UTC, danthewolfe approved these changes
I think this is okay. @jonhartzler can you re-review?

2021-04-08 14:47 UTC, jonhartzler approved these changes

2021-04-08 16:31 UTC, merged