MARBLE-1886 Refactor Card to DisplayCard
ndlib/marble-website-starter pull request #600
Opened 2021-08-31 12:41 UTC by danthewolfe

* Refactor Card component so it doesn't need quite so many weird workarounds.
* `DisplayCard` replaces `Card`
* `MarbleItemCard` replaces `ManifestCard`
* "Empty" card in `CardShell`
* `CardGroup` now accepts an optional array of breakpoint sizes (for adjusting the number of cards when the `CardGroup` is not full width.

See also:

2021-08-31 13:02 UTC, jonhartzler requested changes
I have a few comments that I left in line but mostly what I am wondering about is 2 things.   Since this is such an import section in our code can we get some small usage comments on the top of the components describing what they are used for and props and a few more tests.  We are jumping headfirst into a CD thing here and I am concerned we don't have enough protection for ourselves.   thoughts ?

2021-08-31 15:51 UTC, danthewolfe commented on @ndlib/gatsby-theme-marble/src/components/Shared/DisplayCard/CardBadge/index.js
> +/** @jsx jsx */
Added unit test.

2021-08-31 15:56 UTC, danthewolfe commented on @ndlib/gatsby-theme-marble/src/components/Shared/CardGroup/index.js
>  defaultState - the default state the toggle should be in grid or list
corrected and updated.

2021-08-31 15:57 UTC, danthewolfe commented on @ndlib/gatsby-theme-marble/src/components/Shared/DisplayCard/CardBadge/index.js
> +    default:
added

2021-09-01 15:03 UTC, danthewolfe commented on @ndlib/gatsby-theme-marble/src/components/Shared/DisplayCard/CardShell/LinkOrWrapper/index.js
> +        sx={{
I've moved all the styling to the card to a single `sx.js` file at the root of `DisplayCard`.

2021-09-01 18:20 UTC, jonhartzler approved these changes

2021-09-01 18:30 UTC, merged